
-- Tension and Peace Conferences --
-----------------------------------

NDefines.NDiplomacy.MAX_TRUST_VALUE = 150  -- Vanilla is 100. Max trust value cap.
NDefines.NDiplomacy.MIN_TRUST_VALUE = -150  -- Vanilla is 100. Min trust value cap.
NDefines.NDiplomacy.MAX_OPINION_VALUE = 200 --100						-- Max opinion value cap.
NDefines.NDiplomacy.MIN_OPINION_VALUE = -200    --100
NDefines.NDiplomacy.OPINION_FOR_DEMO_FROM_WT_GENERATION = -0.5  -- Vanilla is -2.0. How much less do democracies like us if we generate world tension


NDefines.NDiplomacy.EMBARGO_THREAT_THRESHOLD = 5  -- Vanilla is 30. Target-generated threat threshold to allow embargo (affected by modifiers)

NDefines.NDiplomacy.TENSION_STATE_VALUE = 1.5  -- Vanilla is 2. Tension value gained by annexing one state
NDefines.NDiplomacy.TENSION_CIVIL_WAR_IMPACT =  0.1--0.2				-- civil war multiplier on tension.
NDefines.NDiplomacy.TENSION_NO_CB_WAR = 8--10,							-- Amount of tension generated by a no-CB wargoal
NDefines.NDiplomacy.TENSION_CB_WAR = 5--7						-- Amount of tension generated by a war with a CB
NDefines.NDiplomacy.TENSION_ANNEX_NO_CLAIM = 1.5--2					-- Amount of tension generated by annexing a state you don't have claims on
NDefines.NDiplomacy.TENSION_ANNEX_CLAIM = 0.25--0.5					-- Amount of tension generated by annexing a state you DO have claims on
NDefines.NDiplomacy.TENSION_ANNEX_CORE = 0--0						-- Amount of tension generated by annexing a state that is your core
NDefines.NDiplomacy.TENSION_PUPPET = 1--1.25						-- Amount of tension generated by puppeting (per state)
NDefines.NDiplomacy.TENSION_FORCE_GOVERNMENT = 0.25 --0.75               -- Amount of tension generated by forcing government (per state)
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.05--0.2			-- Amount of tension generated for each sent division
NDefines.NDiplomacy.TENSION_CAPITULATE = -1 --1
--------------
------------------

NDefines.NDiplomacy.EMBARGO_SAME_IDEOLOGY_AI_WEIGHT = -75  -- Vanilla is -20. AI weight for same ideology
NDefines.NDiplomacy.EMBARGO_DIFFERENT_IDEOLOGY_AI_WEIGHT = -25  -- Vanilla is 15. AI weight for different ideology


NDefines.NAI.DIPLOMACY_CREATE_FACTION_FACTOR = 0.99	--vanila 0.75	-- Factor for AI desire to create a new faction. Val < 1.0 makes it less likely to create than to join.

NDefines.NAI.BASE_RELUCTANCE = 25  -- Vanilla is 20. Base reluctance applied to all diplomatic offers
NDefines.NAI.DIPLOMACY_FACTION_SAME_IDEOLOGY_MAJOR = 20  -- Vanilla is 10. AI bonus acceptance when being asked about faction is a major of the same ideology
NDefines.NAI.DIPLOMACY_FACTION_GLOBAL_TENSION_FACTOR = 0.35  -- Vanilla is 0.2. How much the AI takes global tension into account when considering faction actions
NDefines.NAI.DIPLOMACY_FACTION_WAR_RELUCTANCE = -50 -- Vanilla is -50. Penalty to desire to enter a faction with a country that we are not fighting wars together with.
NDefines.NAI.DIPLOMACY_SCARED_MINOR_EXTRA_RELUCTANCE = -100  -- Vanilla is -50. Extra reluctance to join stuff as scared minor

NDefines.NAI.GENERATE_WARGOAL_THREAT_BASELINE = 0.0
NDefines.NAI.DIPLOMACY_SEND_MAX_FACTION = 0.5
NDefines.NAI.FORCE_FACTOR_AGAINST_EXTRA_MINOR = 0.95		-- AI considers generating wargoals against minors below this % of force compared to themselves to get at a bigger enemy.
NDefines.NAI.MAX_EXTRA_WARGOAL_GENERATION = 3				-- AI may want to generate wargoals against weak minors to get at larger enemy, but never more that this at any given time.
NDefines.NAI.WARGOAL_GENERATION_STRENGTH_FACTOR = 1.5	-- Desire to generate wargoal effected negatevely if actor strength is less than this factor of target strength
NDefines.NAI.DECLARE_WAR_RELATIVE_FORCE_FACTOR = 0.5	-- Weight of relative force between nations that consider going to war
NDefines.NAI.DECLARE_WAR_NOT_NEIGHBOR_FACTOR = 0.25		-- Multiplier applied before force factor if country is not neighbor with the one it is considering going to war
NDefines.NAI.DIPLOMACY_ACCEPT_VOLUNTEERS_BASE = 80  -- Vanilla is 50. Base value of volunteer acceptance (help is welcome)
NDefines.NAI.DIPLOMACY_IMPROVE_RELATION_COST_FACTOR = 10.0  -- Vanilla is 5.0. Desire to boost relations subtracts the cost multiplied by this
NDefines.NAI.DIPLO_ACCEPTABLE_DISTANCE_BETWEEN_CAPITALS = 800.0  -- Vanilla is 1000. When scaled distance malus begins to kick in. At double this value, max penalty (above) is achieved
